### ISSUE TITLE
Heart rate integration fails

### ISSUE THREAD

**Issue by ios-sagar** [lehn0058/ATHeartRate#3]
Hi,

I am new to this thing,
I get your library and checked the code.
It is written awesome. 

I am facing issue to integrate into my code.
I am using Xcode 7.3 and checking on iOS 9.3

Here is my code...

in ViewController.h file
# import <UIKit/UIKit.h>
# import "HeartRateDetectionModel.h"

@interface ViewController : UIViewController <HeartRateDetectionModelDelegate>
@property (nonatomic, strong) HeartRateDetectionModel *hr;
@end

in ViewController.m file
# import "ViewController.h"
# import "HeartRateDetectionModel.h"

@interface ViewController ()

@end

@implementation ViewController

@synthesize hr;
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  
  self.hr = [[HeartRateDetectionModel alloc] init];
  self.hr.delegate = self;
  [self.hr startDetection];
  }
- (void)didReceiveMemoryWarning {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
  }

-(void)heartRateStart
{
    NSLog(@"started!");
}

when I didn't wrote the method "heartRateStart" it was crashing saying "unrecognized selector sent to instance"

now if I do so,
It says
"-[ViewController heartRateUpdate:atTime:]: unrecognized selector sent to instance"

am I following correct guidelines for implementation.
Every time when I integrate your files in any app, do I need to declare all these delegates methods and call to them externally....?

**Comment by lehn0058** [comment]
Yes, you will need to implement the methods in the class you have assigned as the delegate. Implementing the heartRateUpdate method is what returns the updated heart rate to you.
